{buildNpmPackage, nodejs_22, lib}: let
  source = builtins.fetchGit {
    url = "file:///home/hjalte/documents/atdl_learning_site";
    lfs = true;
    rev = "47f16d02ac6025a0880842e7b926ba41f15d221f";
  };

  # Static assets are immutable; keep one reusable store copy outside the
  # npm build tree instead of recopying hundreds of MB per generation.
  staticAssets = builtins.path {
    path = source + "/public";
    name = "atdl-static-assets";
  };
in buildNpmPackage {
  pname = "atdl-learning";
  version = "0.1.0";
  nodejs = nodejs_22;
  src = (lib.cleanSourceWith {
    src = source;
    filter = path: type:
      path != "${source}/public"
      && !(lib.hasPrefix "${source}/public/" path);
  }) // { inherit (source) rev revCount; };

  npmDepsFetcherVersion = 2;
  npmDepsHash = "sha256-adTEJH/q19AvxFudsMRawtRu/plcsTZ7hHL6MZy6b48=";
  ASTRO_TELEMETRY_DISABLED = "1";

  # Keep upstream GitHub Pages defaults while building for the private VPS.
  postPatch = ''
    substituteInPlace astro.config.mjs \
      --replace-fail 'const base = "/atdl_learning_site";' 'const base = "/atdl";' \
      --replace-fail 'https://hjalte01.github.io' 'https://mobile-dev.tail55f864.ts.net'
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/share/atdl-learning
    cp -R dist/. $out/share/atdl-learning/
    # Merge individual asset symlinks: /materials and /papers also have pages
    # generated by Astro, so linking either entire directory would hide them.
    cp -rs ${staticAssets}/. $out/share/atdl-learning/
    runHook postInstall
  '';
}
